hotel_branch model was created
katerina-yarm/pets-hotel pull request #3
Opened 2021-10-30 14:40 UTC by katerina-yarm

The description of the task you can find in Trello ("Create hotel model")

2021-11-01 10:28 UTC, andrewpodolski requested changes

2021-11-01 10:28 UTC, andrewpodolski commented on server/controller/HotelController.js
> +        Hotel_branch.create({
That's common note | It's better to store business logic in **service** package

2021-11-01 10:28 UTC, andrewpodolski commented on server/controller/HotelController.js
> +            name:name,
I think you can leave this object
{
name,
city,
isActive,
address
}

2021-11-01 10:28 UTC, andrewpodolski commented on server/controller/HotelController.js
> +        res.json(`Отель:"${name}" по адресу город ${city}, улица ${address} был успешно создан!`);
I suggest to move all templates in Message.js file

2021-11-01 10:28 UTC, andrewpodolski commented on server/controller/HotelController.js
> +        })
remove console.log pls

2021-11-01 10:28 UTC, andrewpodolski commented on server/controller/HotelController.js
> +/*jshint esversion: 6 */
That's common comment | It's better to use camelCase instead of snake_case

2021-11-01 10:28 UTC, andrewpodolski commented on server/controller/HotelController.js
> +            if(!hotel) return;
It's better to throw some specific message if the hotel wasn't found

2021-11-01 10:28 UTC, andrewpodolski commented on server/controller/HotelController.js
> +                name: name,
The same thing as in createHotel

2021-11-01 10:28 UTC, andrewpodolski commented on server/controller/HotelController.js
> +class HotelController{
I'm not sure that you need to use class. You can just leave functions as you registered only them in routes

2021-11-01 10:28 UTC, andrewpodolski commented on server/controller/HotelController.js
> +    "city":"Витебск",
:)

2021-11-01 10:28 UTC, andrewpodolski commented on server/controller/HotelController.js
> +        }).then(console.log(`Отель с id=${id} успешно удален!`))
**Common Comment** | in successful cases you should throw some message to the controller layer
If there is an error - throw the error to the controller

2021-11-03 11:38 UTC, gitkoshelew commented on server/utils/messages.js
> +	HOTEL_NOT_FOUND,
please, fix indent

2021-11-03 12:15 UTC, merged